### ISSUE TITLE
Multiple Signals

### ISSUE THREAD

**Issue by kiaralherpiniere** [LiamDBailey/climwin#5]
Hi There, 

I just wanted to double check the function below

```
plotall(dataset= dataset,
        datasetrand = Breedwin.RAND,
        bestmodel = SingleWin$BestModel,
        bestmodeldata = SingleWin$BestModelData)
```

 The upper plots show heat maps, and the confidence set. In both of these, if there are two or three seperate signals visible, 
 but for now climwin is grouping them together as one signal, what do you recommend doing? 
 I have what appears to be three signals, and 26% of my models fall within the 95% confidence set. 
 Would you recommend looking at each signal seperately? Or is this indicative that it's not as straight foward as a single signal A having 
 causal effects on trait B? 
 
 You're help is very much ppreiciated. Thank you.

**Comment by LiamDBailey** [comment]
`plotall` is simply showing the output of all the fitted windows and doesn't make any effort to delineate multiple signals if they exist. This is intended behaviour and not an issue with the code. We discuss the possibility of multiple signals in [our paper in Methods in Ecology and Evolution](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12590). In particular, please read p.1252.

In short, multiple signals can often be due to temporal auto-correlation between time-periods, so multiple observable peaks in the plots does not necessarily indicate multiple true signals. One should take the best signal from the original `slidingwin` analysis, fit this into the baseline model and repeat the `slidingwin` analysis. If a second signal still exists following this process this suggests there are true multiple signals. Remember to use `randwin` to account for the impacts of overfitting.

Could you please also post this question in our [Google Group](https://groups.google.com/forum/#!forum/climwin-r-group) so that I can also answer it there?
